name: Python CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Install Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install

      - name: Run tests
        run: poetry run pytest

      - name: Build and upload artifacts
        run: |
          poetry run ts-sdk put task-script private-interview-praveer task-script v1.0.0 ./task-script -f -c ./authentication/ts-sdk-cfg.json
          poetry run ts-sdk put protocol private-interview-praveer task-script v1.0.0 ./protocol -f -c ./authentication/ts-sdk-cfg.json
