name: Python CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Install Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install

      - name: Configure Poetry
        run: |
          python -m poetry config virtualenvs.in-project true

      - name: Cache the virtualenv
        uses: actions/cache@v2
        with:
          path: ./.venv
          key: ${{ runner.os }}-venv-${{ hashFiles('**/poetry.lock') }}

      - name: setup environment
        run: |
          echo "${{ secrets.TS_SDK_CONFIG }}" > auth.json

      - name: Run tests
        run: poetry run pytest

      - name: Build and upload artifacts
        run: |
          cat auth.json
          poetry run python -m ts-sdk put task-script private-interview-praveer task-script v1.0.0 ./task-script -f -c ./auth.json
          poetry run python -m ts-sdk put protocol private-interview-praveer task-script v1.0.0 ./protocol -f -c ./auth.json
